# Generated by Django 5.2 on 2025-04-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djezzy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
